In [5]:
import pandas as pd

raw_df = pd.read_csv("house_sales.csv")
clean_outliers_df = pd.read_csv("cleaned_jordan_outliers.csv")

#clean_no_outliers_df = pd.read_csv("cleaned_house_sales.csv")

In [13]:
def compare_distribution(col):
    raw_stats = raw_df[col].describe()
    clean_stats = clean_outliers_df[col].describe()

    raw_skew = raw_df[col].skew()
    clean_skew = clean_outliers_df[col].skew()

    comparison = pd.concat(
        [raw_stats, clean_stats],
        axis=1
    )

    comparison.columns = ['RAW', 'CLEAN']

    # Add skew row
    comparison.loc['skew'] = [raw_skew, clean_skew]

    print(f"\n===== {col.upper()} DISTRIBUTION =====")
    display(comparison)


key_vars = [
    'price',
    'sqft_living',
    'sqft_lot',
    'bedrooms',
    'bathrooms'
]

for col in key_vars:
    compare_distribution(col)

===== PRICE DISTRIBUTION =====

                RAW         CLEAN
count  2.161300e+04  2.161300e+04
mean   5.400881e+05  5.400881e+05
std    3.671272e+05  3.671272e+05
min    7.500000e+04  7.500000e+04
25%    3.219500e+05  3.219500e+05
50%    4.500000e+05  4.500000e+05
75%    6.450000e+05  6.450000e+05
max    7.700000e+06  7.700000e+06
skew   4.024069e+00  4.024069e+00

===== SQFT_LIVING DISTRIBUTION =====

                RAW         CLEAN
count  20503.000000  21613.000000
mean    2081.073697   2079.899736
std      915.043176    918.440897
min      290.000000    290.000000
25%     1430.000000   1427.000000
50%     1920.000000   1910.000000
75%     2550.000000   2550.000000
max    12050.000000  13540.000000
skew       1.386147      1.471555

===== SQFT_LOT DISTRIBUTION =====

                RAW         CLEAN
count  2.056900e+04  2.161300e+04
mean   1.517982e+04  1.485375e+04
std    4.148617e+04  4.051167e+04
min    5.200000e+02  5.200000e+02
25%    5.040000e+03  5.080000e+03
50%    7.620000e+03  7.663000e+03
75%    1.070800e+04  1.050000e+04
max    1.651359e+06  1.651359e+06
skew   1.287973e+01  1.318743e+01

===== BEDROOMS DISTRIBUTION =====

                RAW         CLEAN
count  20479.000000  21613.000000
mean       3.372821      3.375376
std        0.930711      0.913570
min        0.000000      1.000000
25%        3.000000      3.000000
50%        3.000000      3.000000
75%        4.000000      4.000000
max       33.000000     11.000000
skew       2.022672      0.540461

===== BATHROOMS DISTRIBUTION =====

                RAW         CLEAN
count  20545.000000  21613.000000
mean       2.113507      2.114341
std        0.768913      0.769004
min        0.000000      0.250000
25%        1.500000      1.500000
50%        2.250000      2.250000
75%        2.500000      2.500000
max        8.000000      8.000000
skew       0.504382      0.516530

In [12]:
bed_raw = raw_df['bedrooms'].value_counts(normalize=True).sort_index()
bed_clean = clean_outliers_df['bedrooms'].value_counts(normalize=True).sort_index()

bed_compare = pd.concat(
    [bed_raw, bed_clean],
    axis=1
).fillna(0)

bed_compare.columns = ['RAW', 'CLEAN']

display(bed_compare)

bath_raw = raw_df['bathrooms'].value_counts(normalize=True).sort_index()
bath_clean = clean_outliers_df['bathrooms'].value_counts(normalize=True).sort_index()

bath_compare = pd.concat(
    [bath_raw, bath_clean],
    axis=1
).fillna(0)

bath_compare.columns = ['RAW', 'CLEAN']

display(bath_compare)

               RAW     CLEAN
bedrooms
0.0       0.000537  0.000000
1.0       0.009229  0.009022
2.0       0.127789  0.131402
3.0       0.453440  0.448388
4.0       0.318326  0.318327
5.0       0.075150  0.076621
6.0       0.012842  0.013418
7.0       0.001660  0.001758
8.0       0.000586  0.000648
9.0       0.000244  0.000231
10.0      0.000146  0.000139
33.0      0.000049  0.000000
11.0      0.000000  0.000046

                RAW     CLEAN
bathrooms
0.00       0.000389  0.000000
0.50       0.000195  0.000278
0.75       0.003310  0.004581
1.00       0.178486  0.172489
1.25       0.000389  0.005043
1.50       0.067316  0.070421
1.75       0.141202  0.139314
2.00       0.088975  0.090640
2.25       0.094962  0.095914
2.50       0.248966  0.241521
2.75       0.054563  0.056262
3.00       0.034704  0.035488
3.25       0.027160  0.028594
3.50       0.033585  0.033545
3.75       0.007301  0.007403
4.00       0.006230  0.006246
4.25       0.003748  0.003748
4.50       0.004575  0.004488
4.75       0.001119  0.001157
5.00       0.001022  0.000972
5.25       0.000487  0.000463
5.50       0.000487  0.000509
5.75       0.000146  0.000185
6.00       0.000243  0.000278
6.25       0.000097  0.000093
6.50       0.000097  0.000093
6.75       0.000049  0.000046
7.50       0.000049  0.000046
7.75       0.000049  0.000046
8.00       0.000097  0.000093
0.25       0.000000  0.000046

In [25]:
print((raw_df['view'] > 0).sum())
print((raw_df['view'] > 0).mean() * 100)

display(raw_df['view'].value_counts().sort_index())

display(raw_df['view'].value_counts(normalize=True).sort_index())

2124
9.827418683199927

view
0    19489
1      332
2      963
3      510
4      319
Name: count, dtype: int64

view
0    0.901726
1    0.015361
2    0.044557
3    0.023597
4    0.014760
Name: proportion, dtype: float64